[minio]
minio01 ansible_host=192.168.-.-
minio02 ansible_host=192.168.-.-
minio03 ansible_host=192.168.-.-
minio04 ansible_host=192.168.-.-

[ELK]
elk01 ansible_host=192.168.-.-
elk02 ansible_host=192.168.-.-
elk03 ansible_host=192.168.-.-

[DB]
db01 ansible_host=192.168.-.-
